-- =============================================
-- SCRIPT COMPLETO DE CONFIGURACIÓN BM2PELIS
-- =============================================

-- 1. CONECTAR COMO SYS Y CREAR USUARIO HR
-- sqlplus sys/password@localhost:1521/XEPDB1 as sysdba
-- CREATE USER HR IDENTIFIED BY HR;
-- GRANT CONNECT, RESOURCE, DBA TO HR;
-- GRANT CREATE SESSION TO HR;
-- GRANT UNLIMITED TABLESPACE TO HR;

-- 2. CONECTAR COMO HR
-- sqlplus HR/HR@localhost:1521/XEPDB1

-- 3. LIMPIAR ESQUEMA EXISTENTE
BEGIN
  FOR obj IN (
    SELECT object_name, object_type FROM user_objects 
    WHERE object_type IN ('VIEW','TABLE','SEQUENCE','PROCEDURE','FUNCTION','PACKAGE','PACKAGE BODY','TRIGGER','SYNONYM')
  ) LOOP
    BEGIN
      IF obj.object_type = 'TABLE' THEN
        EXECUTE IMMEDIATE 'DROP TABLE "' || obj.object_name || '" CASCADE CONSTRAINTS PURGE';
      ELSE
        EXECUTE IMMEDIATE 'DROP ' || obj.object_type || ' "' || obj.object_name || '"';
      END IF;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

-- 4. CREAR TABLAS
CREATE TABLE Usuarios (
  id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre NVARCHAR2(100),
  correo NVARCHAR2(150) UNIQUE NOT NULL,
  contrasena NVARCHAR2(200) NOT NULL,
  rol NVARCHAR2(20) DEFAULT 'user'
);

CREATE TABLE Peliculas (
  id_pelicula NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo NVARCHAR2(150),
  genero NVARCHAR2(100),
  tipo NVARCHAR2(50),
  anio NUMBER(4),
  descripcion NVARCHAR2(500),
  imagen NVARCHAR2(255)
);

CREATE TABLE Alquileres (
  id_alquiler NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario NUMBER REFERENCES Usuarios(id_usuario),
  id_pelicula NUMBER REFERENCES Peliculas(id_pelicula),
  fecha_alquiler DATE DEFAULT SYSDATE,
  estado NVARCHAR2(20)
);

CREATE TABLE Suscripciones (
  id_suscripcion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario NUMBER REFERENCES Usuarios(id_usuario),
  tipo NVARCHAR2(50),
  fecha_inicio DATE DEFAULT SYSDATE,
  fecha_fin DATE
);

CREATE TABLE Pagos (
  id_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario NUMBER REFERENCES Usuarios(id_usuario),
  tipo NVARCHAR2(50),
  monto NUMBER(10,2),
  fecha_pago DATE DEFAULT SYSDATE,
  metodo NVARCHAR2(50),
  estado NVARCHAR2(20) DEFAULT 'Completado'
);

CREATE TABLE Facturas (
  id_factura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pago NUMBER REFERENCES Pagos(id_pago),
  id_usuario NUMBER REFERENCES Usuarios(id_usuario),
  detalle NVARCHAR2(255),
  total NUMBER(10,2),
  fecha_emision DATE DEFAULT SYSDATE
);

CREATE TABLE Tickets (
  id_ticket NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario NUMBER REFERENCES Usuarios(id_usuario),
  asunto NVARCHAR2(150),
  descripcion NVARCHAR2(1000),
  estado NVARCHAR2(20) DEFAULT 'Abierto',
  fecha_creacion DATE DEFAULT SYSDATE
);

CREATE TABLE Mensajes (
  id_mensaje NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ticket NUMBER REFERENCES Tickets(id_ticket),
  emisor NVARCHAR2(20),
  contenido NVARCHAR2(1000),
  fecha_envio DATE DEFAULT SYSDATE
);

-- 5. INSERTAR DATOS INICIALES

-- Películas, Series y Juegos
INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Horizonte Rojo', 'Acción', 'Película', 2023, 'Un agente lucha contra un sistema corrupto.', 'pelicula_HorizonteRojo.png');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Sombras Eternas', 'Terror', 'Película', 2022, 'Una familia enfrenta su pasado en una casa maldita.', 'pelicula_SombrasEternas.png');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Tiempo Muerto', 'Ciencia Ficción', 'Serie', 2024, 'Viajes en el tiempo con consecuencias impredecibles.', 'serie_TiempoMuerto.png');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Guardianes del Alba', 'Fantasía', 'Serie', 2023, 'Un grupo de héroes lucha contra la oscuridad.', 'serie_GuardianesDelAlba.png');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Neon City', 'Acción', 'Juego', 2022, 'Aventura cyberpunk llena de batallas y caos.', 'juego_NeonCity.png');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Reino Perdido', 'Aventura', 'Juego', 2023, 'Explora un mundo olvidado lleno de misterios.', 'juego_ReinoPerdido.png');

-- Más contenido
INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('El Padrino', 'Drama', 'Película', 1972, 'La historia de una familia de la mafia italiana.', 'pelicula_ElPadrino.jpg');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Breaking Bad', 'Drama', 'Serie', 2008, 'Un profesor de química se convierte en narcotraficante.', 'serie_BreakingBad.jpg');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('The Witcher 3', 'RPG', 'Juego', 2015, 'Aventura épica en un mundo de fantasía.', 'juego_TheWitcher3.jpg');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Stranger Things', 'Terror', 'Serie', 2016, 'Un grupo de niños enfrenta fuerzas sobrenaturales.', 'serie_StrangerThings.jpg');

INSERT INTO Peliculas (titulo, genero, tipo, anio, descripcion, imagen) VALUES
('Cyberpunk 2077', 'Acción', 'Juego', 2020, 'RPG de mundo abierto en un futuro distópico.', 'juego_Cyberpunk2077.jpg');

-- Usuario administrador (contraseña: admin123)
INSERT INTO Usuarios (nombre, correo, contrasena, rol) VALUES
('Administrador', 'admin@bm2pelis.com', '$2b$10$rQZ8K9vL2mN3oP4qR5sT6uV7wX8yZ9aB0cD1eF2gH3iJ4kL5mN6oP7qR8sT9uV', 'admin');

-- Usuario de prueba (contraseña: user123)
INSERT INTO Usuarios (nombre, correo, contrasena, rol) VALUES
('Usuario Prueba', 'user@bm2pelis.com', '$2b$10$rQZ8K9vL2mN3oP4qR5sT6uV7wX8yZ9aB0cD1eF2gH3iJ4kL5mN6oP7qR8sT9uV', 'user');

-- Suscripciones de ejemplo
INSERT INTO Suscripciones (id_usuario, tipo, fecha_inicio, fecha_fin) VALUES
(1, 'Premium', SYSDATE, SYSDATE + 30);

INSERT INTO Suscripciones (id_usuario, tipo, fecha_inicio, fecha_fin) VALUES
(2, 'Básica', SYSDATE, SYSDATE + 15);

-- Pagos de ejemplo
INSERT INTO Pagos (id_usuario, tipo, monto, fecha_pago, metodo, estado) VALUES
(1, 'Suscripción', 15.99, SYSDATE, 'Tarjeta', 'Completado');

INSERT INTO Pagos (id_usuario, tipo, monto, fecha_pago, metodo, estado) VALUES
(2, 'Alquiler', 3.99, SYSDATE, 'PayPal', 'Completado');

-- Alquileres de ejemplo
INSERT INTO Alquileres (id_usuario, id_pelicula, fecha_alquiler, estado) VALUES
(1, 1, SYSDATE, 'Activo');

INSERT INTO Alquileres (id_usuario, id_pelicula, fecha_alquiler, estado) VALUES
(2, 3, SYSDATE, 'Activo');

-- Tickets de ejemplo
INSERT INTO Tickets (id_usuario, asunto, descripcion, estado, fecha_creacion) VALUES
(1, 'Problema con reproducción', 'No puedo reproducir la película Horizonte Rojo', 'Abierto', SYSDATE);

INSERT INTO Tickets (id_usuario, asunto, descripcion, estado, fecha_creacion) VALUES
(2, 'Solicitud de reembolso', 'Quiero cancelar mi suscripción', 'En Proceso', SYSDATE);

-- Mensajes de ejemplo
INSERT INTO Mensajes (id_ticket, emisor, contenido, fecha_envio) VALUES
(1, 'user', 'Hola, tengo problemas para reproducir la película', SYSDATE);

INSERT INTO Mensajes (id_ticket, emisor, contenido, fecha_envio) VALUES
(1, 'admin', 'Hola, revisaremos tu problema. ¿Podrías verificar tu conexión a internet?', SYSDATE);

-- Confirmar cambios
COMMIT;

-- Verificar datos
SELECT 'Usuarios' as tabla, COUNT(*) as registros FROM Usuarios
UNION ALL
SELECT 'Peliculas', COUNT(*) FROM Peliculas
UNION ALL
SELECT 'Alquileres', COUNT(*) FROM Alquileres
UNION ALL
SELECT 'Suscripciones', COUNT(*) FROM Suscripciones
UNION ALL
SELECT 'Pagos', COUNT(*) FROM Pagos
UNION ALL
SELECT 'Tickets', COUNT(*) FROM Tickets
UNION ALL
SELECT 'Mensajes', COUNT(*) FROM Mensajes;

-- Mostrar mensaje de éxito
SELECT 'Base de datos BM2Pelis configurada exitosamente!' as mensaje FROM DUAL;
